/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cities */
        get: operations["listCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Health */
        get: operations["checkHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/housing-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Housing Providers */
        get: operations["listHousingProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/lead-time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead Time Summary */
        get: operations["getLeadTimeSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outcomes/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outcome Summary */
        get: operations["getOutcomeSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pilot/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record Pilot Activity */
        put: operations["recordPilotActivity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pilot/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pilot Metrics */
        get: operations["getPilotMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pilot/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pilot Signals */
        get: operations["listPilotSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pilot/signals/{signal_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pilot Signal Feedback */
        get: operations["getPilotSignalFeedback"];
        /** Upsert Pilot Signal Feedback */
        put: operations["upsertPilotSignalFeedback"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Property */
        get: operations["getProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quality/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quality Summary */
        get: operations["getQualitySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rental-coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rental Coverage */
        get: operations["getRentalCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rental-listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rental Listings */
        get: operations["listRentalListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rental-listings/{listing_id}/classifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rental Listing Classifications */
        get: operations["listRentalListingClassifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rental-listings/{listing_id}/measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rental Listing Measurements */
        get: operations["listRentalListingMeasurements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rental-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rental Projects */
        get: operations["listRentalProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/score-activations/{scope_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Score Activation Set */
        get: operations["getScoreActivationSet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/score-activations/{scope_key}/signals/{signal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Signal Dimensions */
        get: operations["getActiveSignalDimensions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/score-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Score Runs */
        get: operations["listScoreRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/score-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Score Run */
        get: operations["getScoreRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/score-runs/{run_id}/signals/{signal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Score Run Signal Dimensions */
        get: operations["getScoreRunSignalDimensions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Signals */
        get: operations["listSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/{signal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Signal */
        get: operations["getSignal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/{signal_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Signal Outcomes */
        get: operations["listSignalOutcomes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Runs */
        get: operations["listSourceRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_key}/lifecycle-readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Lifecycle Readiness */
        get: operations["getSourceLifecycleReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spatial-features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Spatial Features */
        get: operations["listSpatialFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Validation Batches */
        get: operations["listValidationBatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation-batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Validation Batch */
        get: operations["getValidationBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivatedScoreDefinitionOut */
        ActivatedScoreDefinitionOut: {
            /**
             * Activated At
             * Format: date-time
             */
            activated_at: string;
            /** Decision Reason */
            decision_reason: string;
            definition: components["schemas"]["ScoreDefinitionOut"];
            /** Dimension */
            dimension: string;
        };
        /** ActiveDimensionsOut */
        ActiveDimensionsOut: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Data Confidence */
            data_confidence: number;
            /** Definition Set Hash */
            definition_set_hash: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Signal Strength */
            signal_strength: number;
            /** Timing */
            timing: number;
        };
        /** AddressEnrichmentOut */
        AddressEnrichmentOut: {
            /** Attribution */
            attribution: string;
            /** Canonical Address */
            canonical_address: string;
            /** Data Mode */
            data_mode: string;
            /**
             * External Address Id
             * Format: uuid
             */
            external_address_id: string;
            /** Municipality Code */
            municipality_code: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Postal Code */
            postal_code: string | null;
            /** Postal Town */
            postal_town: string | null;
            register_unit?: components["schemas"]["RegisterUnitReferenceOut"] | null;
            /** Source */
            source: string;
            /** Source Easting */
            source_easting: string;
            /** Source Northing */
            source_northing: string;
            /** Source Srid */
            source_srid: number;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CityOut */
        CityOut: {
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: number;
            /** Municipality Code */
            municipality_code: string;
            /** Name */
            name: string;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Effective Date */
            effective_date: string | null;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Raw Item Id
             * Format: uuid
             */
            raw_item_id: string;
            /** Reason */
            reason: string;
            /** Source */
            source: string;
            /** Source Item Id */
            source_item_id: string;
            /** Weight */
            weight: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HousingProviderList */
        HousingProviderList: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["HousingProviderOut"][];
        };
        /** HousingProviderOut */
        HousingProviderOut: {
            /** Channels */
            channels: components["schemas"]["ProviderChannelOut"][];
            /** City */
            city: string;
            /** Discovery Source */
            discovery_source: string;
            /** Evidence Url */
            evidence_url: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Official Url */
            official_url: string;
            /** Provider Type */
            provider_type: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
        };
        /** LeadTimeSummaryOut */
        LeadTimeSummaryOut: {
            /** Classification Tag */
            classification_tag: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Invalid Input Count */
            invalid_input_count: number;
            /** Late Count */
            late_count: number;
            /** Listing Status */
            listing_status: string | null;
            /** Max Days */
            max_days: string | null;
            /** Measured Count */
            measured_count: number;
            /** Measurement Count */
            measurement_count: number;
            /** Median Days */
            median_days: string | null;
            /** Min Days */
            min_days: string | null;
            /** Missing Input Count */
            missing_input_count: number;
            /** Population Count */
            population_count: number;
            /** Rule Version */
            rule_version: string;
            /** Source Key */
            source_key: string | null;
        };
        /** LifecycleReadinessOut */
        LifecycleReadinessOut: {
            /** Considered Run Ids */
            considered_run_ids: string[];
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            /** Latest Scheduled Run At */
            latest_scheduled_run_at: string | null;
            /** Qualifying Runs */
            qualifying_runs: number;
            /** Reasons */
            reasons: string[];
            /** Required Runs */
            required_runs: number;
            /** Rule Version */
            rule_version: string | null;
            /** Source Key */
            source_key: string;
            /** Status */
            status: string;
        };
        /** ListingMeasurementOut */
        ListingMeasurementOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            /** Metric */
            metric: string;
            /** Rule Version */
            rule_version: string;
            /** Status */
            status: string;
            /** Unit */
            unit: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value */
            value: string | null;
        };
        /** OutcomeSummaryItem */
        OutcomeSummaryItem: {
            /** Count */
            count: number;
            /** Outcome Type */
            outcome_type: string;
            /** Subject */
            subject: string;
            /** Verification Level */
            verification_level: string;
        };
        /** OutcomeSummaryOut */
        OutcomeSummaryOut: {
            /** Confirmed Move Count */
            confirmed_move_count: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Items */
            items: components["schemas"]["OutcomeSummaryItem"][];
            /** Outcome Count */
            outcome_count: number;
            /** Signal Population Count */
            signal_population_count: number;
            /** Signals With Outcomes */
            signals_with_outcomes: number;
        };
        /** PilotActivityRecordedOut */
        PilotActivityRecordedOut: {
            activity_type: components["schemas"]["PilotActivityType"];
            /** Recorded Count */
            recorded_count: number;
        };
        /**
         * PilotActivityType
         * @enum {string}
         */
        PilotActivityType: "SHOWN" | "OPENED";
        /** PilotActivityUpsert */
        PilotActivityUpsert: {
            activity_type: components["schemas"]["PilotActivityType"];
            /**
             * Cohort As Of Date
             * Format: date
             */
            cohort_as_of_date: string;
            /** Cohort Version */
            cohort_version: string;
            /** Definition Set Hash */
            definition_set_hash: string;
            /** Dimension Scope Key */
            dimension_scope_key: string;
            /** Pilot Key */
            pilot_key: string;
            /**
             * Score As Of Date
             * Format: date
             */
            score_as_of_date: string;
            /**
             * Score Run Id
             * Format: uuid
             */
            score_run_id: string;
            /** Signal Ids */
            signal_ids: string[];
        };
        /** PilotCohortCriteriaOut */
        PilotCohortCriteriaOut: {
            /**
             * Active Signals Only
             * @default true
             * @constant
             */
            active_signals_only: true;
            /** City Id */
            city_id: number;
            /**
             * Dated Signals Only
             * @default true
             * @constant
             */
            dated_signals_only: true;
            /**
             * Live Evidence Required
             * @default true
             * @constant
             */
            live_evidence_required: true;
            /** Move Horizon Days */
            move_horizon_days: number;
            /** Signal Age Days */
            signal_age_days: number;
        };
        /** PilotFeedbackOut */
        PilotFeedbackOut: {
            /**
             * Cohort As Of Date
             * Format: date
             */
            cohort_as_of_date: string;
            /** Cohort Version */
            cohort_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data Confidence At Review */
            data_confidence_at_review: number;
            /** Definition Set Hash */
            definition_set_hash: string;
            /** Dimension Scope Key */
            dimension_scope_key: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Note */
            note: string | null;
            /** Pilot Key */
            pilot_key: string;
            reason: components["schemas"]["PilotFeedbackReason"];
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /**
             * Score As Of Date
             * Format: date
             */
            score_as_of_date: string;
            /**
             * Score Run Id
             * Format: uuid
             */
            score_run_id: string;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
            /** Signal Strength At Review */
            signal_strength_at_review: number;
            /** Timing At Review */
            timing_at_review: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            verdict: components["schemas"]["PilotFeedbackVerdict"];
        };
        /**
         * PilotFeedbackReason
         * @enum {string}
         */
        PilotFeedbackReason: "GOOD_OPPORTUNITY" | "TOO_EARLY" | "TOO_LATE" | "WRONG_PROPERTY" | "WEAK_SIGNAL" | "DUPLICATE" | "OUTSIDE_SERVICE_AREA" | "INSUFFICIENT_CONTEXT";
        /** PilotFeedbackUpsert */
        PilotFeedbackUpsert: {
            /**
             * Cohort As Of Date
             * Format: date
             */
            cohort_as_of_date: string;
            /** Cohort Version */
            cohort_version: string;
            /** Definition Set Hash */
            definition_set_hash: string;
            /** Dimension Scope Key */
            dimension_scope_key: string;
            /** Note */
            note?: string | null;
            /** Pilot Key */
            pilot_key: string;
            reason: components["schemas"]["PilotFeedbackReason"];
            /**
             * Score As Of Date
             * Format: date
             */
            score_as_of_date: string;
            /**
             * Score Run Id
             * Format: uuid
             */
            score_run_id: string;
            verdict: components["schemas"]["PilotFeedbackVerdict"];
        };
        /**
         * PilotFeedbackVerdict
         * @enum {string}
         */
        PilotFeedbackVerdict: "USEFUL" | "MAYBE" | "NOT_USEFUL";
        /** PilotMetricsOut */
        PilotMetricsOut: {
            /**
             * Cohort As Of Date
             * Format: date
             */
            cohort_as_of_date: string;
            /** Cohort Version */
            cohort_version: string;
            /** Definition Set Hash */
            definition_set_hash: string;
            /** Dimension Scope Key */
            dimension_scope_key: string;
            /** Maybe */
            maybe: number;
            /** Not Useful */
            not_useful: number;
            /** Open Rate */
            open_rate: number | null;
            /** Opened */
            opened: number;
            /** Pilot Key */
            pilot_key: string;
            /** Reason Counts */
            reason_counts: {
                [key: string]: number;
            };
            /** Review Rate */
            review_rate: number | null;
            /** Reviewed */
            reviewed: number;
            /**
             * Score As Of Date
             * Format: date
             */
            score_as_of_date: string;
            /**
             * Score Run Id
             * Format: uuid
             */
            score_run_id: string;
            /** Shown */
            shown: number;
            /** Useful */
            useful: number;
            /** Useful Rate */
            useful_rate: number | null;
        };
        /** PilotPaginationOut */
        PilotPaginationOut: {
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PilotSignalFeedbackSummaryOut */
        PilotSignalFeedbackSummaryOut: {
            reason: components["schemas"]["PilotFeedbackReason"];
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            verdict: components["schemas"]["PilotFeedbackVerdict"];
        };
        /** PilotSignalFiltersOut */
        PilotSignalFiltersOut: {
            /** Address Query */
            address_query: string | null;
            /** Center Latitude */
            center_latitude: string | null;
            /** Center Longitude */
            center_longitude: string | null;
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
            /** Max Area M2 */
            max_area_m2: string | null;
            /** Max Rooms */
            max_rooms: string | null;
            /** Min Area M2 */
            min_area_m2: string | null;
            /** Min Rooms */
            min_rooms: string | null;
            /** Property Type */
            property_type: string | null;
            /** Radius Km */
            radius_km: string | null;
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "ALL" | "REVIEWED" | "UNREVIEWED";
            /** Signal Type */
            signal_type: string | null;
            /** Strength Band */
            strength_band: ("LOW" | "MEDIUM" | "HIGH") | null;
        };
        /** PilotSignalListOut */
        PilotSignalListOut: {
            applied_filters: components["schemas"]["PilotSignalFiltersOut"];
            /**
             * Cohort As Of Date
             * Format: date
             */
            cohort_as_of_date: string;
            /** Cohort Version */
            cohort_version: string;
            /** Count */
            count: number;
            criteria: components["schemas"]["PilotCohortCriteriaOut"];
            /** Definition Set Hash */
            definition_set_hash: string;
            /** Dimension Scope Key */
            dimension_scope_key: string;
            /** Items */
            items: components["schemas"]["PilotSignalOut"][];
            pagination: components["schemas"]["PilotPaginationOut"];
            /**
             * Score As Of Date
             * Format: date
             */
            score_as_of_date: string;
            /**
             * Score Run Id
             * Format: uuid
             */
            score_run_id: string;
            /**
             * Sort
             * @enum {string}
             */
            sort: "PRIORITY" | "MOVE_WINDOW" | "NEWEST";
            summary: components["schemas"]["PilotSignalSummaryOut"];
            /** Total */
            total: number;
        };
        /** PilotSignalOut */
        PilotSignalOut: {
            active_dimensions: components["schemas"]["ActiveDimensionsOut"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Days Until Window Start */
            days_until_window_start: number;
            /** Estimated Move From */
            estimated_move_from: string | null;
            /** Estimated Move To */
            estimated_move_to: string | null;
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Evidence Count */
            evidence_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            pilot_feedback?: components["schemas"]["PilotSignalFeedbackSummaryOut"] | null;
            property: components["schemas"]["PropertyOut"];
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /** Signal Age Days */
            signal_age_days: number;
            /** Signal Type */
            signal_type: string;
            /** Status */
            status: string;
            /**
             * Strength Band
             * @enum {string}
             */
            strength_band: "LOW" | "MEDIUM" | "HIGH";
            timing?: components["schemas"]["SignalTimingOut"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PilotSignalSummaryOut */
        PilotSignalSummaryOut: {
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Mapped */
            mapped: number;
            /** Medium */
            medium: number;
            /** Next 30 Days */
            next_30_days: number;
            /** Total */
            total: number;
        };
        /** PropertyOut */
        PropertyOut: {
            /** Address */
            address: string;
            /**
             * Address Enrichments
             * @default []
             */
            address_enrichments: components["schemas"]["AddressEnrichmentOut"][];
            /** Area M2 */
            area_m2: string | null;
            /** City */
            city: string;
            /** City Id */
            city_id: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latitude */
            latitude: string | null;
            /** Longitude */
            longitude: string | null;
            /** Municipality Code */
            municipality_code: string;
            /** New Construction */
            new_construction: boolean | null;
            /** Property Type */
            property_type: string;
            /** Rooms */
            rooms: string | null;
            /** Unit Identifier */
            unit_identifier: string | null;
        };
        /** ProviderChannelOut */
        ProviderChannelOut: {
            /** Channel Key */
            channel_key: string;
            /** Channel Type */
            channel_type: string;
            /** Collection Status */
            collection_status: string;
            /** Coverage */
            coverage: string;
            /** Is Primary */
            is_primary: boolean;
            /** Next Action */
            next_action: string | null;
            /** Publisher Name */
            publisher_name: string;
            /** Requires Agreement */
            requires_agreement: boolean;
            /** Requires Auth */
            requires_auth: boolean;
            /** Source Key */
            source_key: string | null;
            /** Url */
            url: string;
        };
        /** QualityFindingOut */
        QualityFindingOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
        };
        /** QualityRatioOut */
        QualityRatioOut: {
            /** Denominator */
            denominator: number;
            /** Numerator */
            numerator: number;
            /** Percent */
            percent: string | null;
        };
        /** QualitySourceOut */
        QualitySourceOut: {
            /** Active Listing Count */
            active_listing_count: number;
            /** Completeness Rule Version */
            completeness_rule_version: string | null;
            /** Latest Execution Status */
            latest_execution_status: string | null;
            /** Latest Run At */
            latest_run_at: string | null;
            /** Latest Snapshot Status */
            latest_snapshot_status: string | null;
            /** Missing Available From Count */
            missing_available_from_count: number;
            /** Source Key */
            source_key: string;
            /** Source Name */
            source_name: string;
            /** Unique Property Count */
            unique_property_count: number;
        };
        /** QualityStrengthBucketOut */
        QualityStrengthBucketOut: {
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Max Strength */
            max_strength: number;
            /** Min Strength */
            min_strength: number;
        };
        /** QualitySummaryOut */
        QualitySummaryOut: {
            /** Active Signal Count */
            active_signal_count: number;
            ambiguous_match_rate: components["schemas"]["QualityRatioOut"];
            /** Average Evidence Count */
            average_evidence_count: string | null;
            /** City */
            city: string;
            /** City Id */
            city_id: number;
            classification_coverage: components["schemas"]["QualityRatioOut"];
            /** Closed Signal Count */
            closed_signal_count: number;
            /** Confirmed Move Count */
            confirmed_move_count: number;
            cross_source_property_overlap_rate: components["schemas"]["QualityRatioOut"];
            /** Data Mode */
            data_mode: string;
            /** Findings */
            findings: components["schemas"]["QualityFindingOut"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Listing Population Count */
            listing_population_count: number;
            measurement_record_coverage: components["schemas"]["QualityRatioOut"];
            /** Median Lead Time Days */
            median_lead_time_days: string | null;
            /** Median Signal Age Days */
            median_signal_age_days: string | null;
            missing_available_from_rate: components["schemas"]["QualityRatioOut"];
            /** Outcome Count */
            outcome_count: number;
            outcome_coverage: components["schemas"]["QualityRatioOut"];
            /** Rule Version */
            rule_version: string;
            same_source_duplicate_rate: components["schemas"]["QualityRatioOut"];
            /** Signal Population Count */
            signal_population_count: number;
            /** Signal Strength Distribution */
            signal_strength_distribution: components["schemas"]["QualityStrengthBucketOut"][];
            /** Sources */
            sources: components["schemas"]["QualitySourceOut"][];
            /** Strong Signal Count */
            strong_signal_count: number;
            /** Unique Property Count */
            unique_property_count: number;
            unknown_classification_rate: components["schemas"]["QualityRatioOut"];
            usable_lead_time_rate: components["schemas"]["QualityRatioOut"];
        };
        /** RegisterUnitReferenceOut */
        RegisterUnitReferenceOut: {
            /** Designation */
            designation: string;
            /**
             * External Register Unit Id
             * Format: uuid
             */
            external_register_unit_id: string;
            /** Register Unit Type */
            register_unit_type: string;
        };
        /** RentalCoverageOut */
        RentalCoverageOut: {
            /** City */
            city: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Known Provider Count */
            known_provider_count: number;
            /** Missing Known Provider Count */
            missing_known_provider_count: number;
            /** Observed Provider Count */
            observed_provider_count: number;
            /** Providers */
            providers: components["schemas"]["RentalCoverageProviderOut"][];
            /** Represented Known Provider Count */
            represented_known_provider_count: number;
        };
        /** RentalCoverageProviderOut */
        RentalCoverageProviderOut: {
            /** Collector Keys */
            collector_keys: string[];
            /** Gap Reason */
            gap_reason: string | null;
            /** Key */
            key: string;
            /** Known Provider */
            known_provider: boolean;
            /** Live Listing Count */
            live_listing_count: number;
            /** Name */
            name: string;
            /** Publishers */
            publishers: string[];
            /** Status */
            status: string;
        };
        /** RentalListingClassificationOut */
        RentalListingClassificationOut: {
            /** Confidence */
            confidence: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /** Reason */
            reason: string;
            /** Rule Version */
            rule_version: string;
            /** Tag */
            tag: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RentalListingList */
        RentalListingList: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["RentalListingOut"][];
        };
        /** RentalListingOut */
        RentalListingOut: {
            /** Application Deadline */
            application_deadline: string | null;
            /** Area M2 */
            area_m2: string | null;
            /** Attribution */
            attribution: string;
            /** Available From */
            available_from: string | null;
            /** Canonical Url */
            canonical_url: string | null;
            /** Categories */
            categories: string[];
            /** Data Mode */
            data_mode: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Monthly Rent */
            monthly_rent: string | null;
            /** New Construction */
            new_construction: boolean | null;
            property: components["schemas"]["PropertyOut"];
            /** Publisher */
            publisher: string;
            /** Removed At */
            removed_at: string | null;
            /** Rooms */
            rooms: string | null;
            /** Source Item Id */
            source_item_id: string;
            /** Status */
            status: string;
            /** Unit Identifier */
            unit_identifier: string | null;
            /** Upstream Provider Key */
            upstream_provider_key: string;
            /** Upstream Provider Name */
            upstream_provider_name: string;
        };
        /** RentalProjectList */
        RentalProjectList: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["RentalProjectOut"][];
        };
        /** RentalProjectOut */
        RentalProjectOut: {
            /** Active Listing Count */
            active_listing_count: number;
            /** Address */
            address: string;
            /** Area Max */
            area_max: string | null;
            /** Area Min */
            area_min: string | null;
            /** Attribution */
            attribution: string;
            /** Available From */
            available_from: string | null;
            /** Canonical Url */
            canonical_url: string;
            /** City */
            city: string;
            /** Data Mode */
            data_mode: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Imported Listing Count */
            imported_listing_count: number;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Name */
            name: string;
            /** Planned Unit Count */
            planned_unit_count: number | null;
            /** Rent Max */
            rent_max: string | null;
            /** Rent Min */
            rent_min: string | null;
            /** Rooms Max */
            rooms_max: string | null;
            /** Rooms Min */
            rooms_min: string | null;
            /** Source Item Id */
            source_item_id: string;
            /** Status */
            status: string;
            /** Upstream Provider Key */
            upstream_provider_key: string;
            /** Upstream Provider Name */
            upstream_provider_name: string;
        };
        /** ScoreActivationSetOut */
        ScoreActivationSetOut: {
            /** Activations */
            activations: components["schemas"]["ActivatedScoreDefinitionOut"][];
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** City Id */
            city_id: number;
            /**
             * Decision Run Id
             * Format: uuid
             */
            decision_run_id: string;
            /** Scope Key */
            scope_key: string;
            /**
             * Scope Type
             * @constant
             */
            scope_type: "INTERNAL_PILOT";
            /**
             * Serving Mode
             * @default INTERNAL_PILOT
             * @constant
             */
            serving_mode: "INTERNAL_PILOT";
        };
        /** ScoreDefinitionOut */
        ScoreDefinitionOut: {
            /** Definition Revision */
            definition_revision: string;
            /** Dimension */
            dimension: string;
            /** Engine Revision */
            engine_revision: string;
            /** Feature Schema Revision */
            feature_schema_revision: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parameter Hash */
            parameter_hash: string;
            /** Status */
            status: string;
        };
        /** ScoreRunOut */
        ScoreRunOut: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** City Id */
            city_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Definition Set Hash */
            definition_set_hash: string;
            /** Feature Schema Revision */
            feature_schema_revision: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Population Fingerprint */
            population_fingerprint: string;
            /** Population Size */
            population_size: number;
            /** Status */
            status: string;
        };
        /** SignalDimensionEvaluationOut */
        SignalDimensionEvaluationOut: {
            /** Components */
            components: {
                [key: string]: unknown;
            }[];
            definition: components["schemas"]["ScoreDefinitionOut"];
            /** Dimension */
            dimension: string;
            /** Score */
            score: number;
            /** Warnings */
            warnings: string[];
        };
        /** SignalDimensionSetOut */
        SignalDimensionSetOut: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Dimensions */
            dimensions: components["schemas"]["SignalDimensionEvaluationOut"][];
            /** Feature Snapshot Hash */
            feature_snapshot_hash: string;
            /**
             * Feature Snapshot Id
             * Format: uuid
             */
            feature_snapshot_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
        };
        /** SignalList */
        SignalList: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["SignalOut"][];
        };
        /** SignalOut */
        SignalOut: {
            active_dimensions: components["schemas"]["ActiveDimensionsOut"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Estimated Move From */
            estimated_move_from: string | null;
            /** Estimated Move To */
            estimated_move_to: string | null;
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Evidence Count */
            evidence_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            property: components["schemas"]["PropertyOut"];
            /**
             * Property Id
             * Format: uuid
             */
            property_id: string;
            /** Signal Type */
            signal_type: string;
            /** Status */
            status: string;
            timing?: components["schemas"]["SignalTimingOut"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SignalOutcomeOut */
        SignalOutcomeOut: {
            /** Confidence */
            confidence: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dedupe Key */
            dedupe_key: string;
            /** Event Id */
            event_id: string | null;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Listing Id */
            listing_id: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Outcome Type */
            outcome_type: string;
            /** Rule Version */
            rule_version: string;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
            /** Subject */
            subject: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Verification Level */
            verification_level: string;
        };
        /** SignalTimingOut */
        SignalTimingOut: {
            /** As Of */
            as_of: string | null;
            /** Facts */
            facts: components["schemas"]["TimingFactOut"][];
            /** Mode */
            mode: string;
            primary: components["schemas"]["TimingFactOut"];
            /** Warnings */
            warnings: string[];
        };
        /** SignalValidationOut */
        SignalValidationOut: {
            /** Classification Tags */
            classification_tags: string[];
            /** Data Confidence At Selection */
            data_confidence_at_selection: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Inclusion Reasons */
            inclusion_reasons: string[];
            /** Issue Codes */
            issue_codes: string[];
            /** Notes */
            notes: string | null;
            /** Provider Keys */
            provider_keys: string[];
            /** Review Status */
            review_status: string;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Reviewer */
            reviewer: string | null;
            /** Score At Selection */
            score_at_selection: number | null;
            /** Score Stratum */
            score_stratum: string | null;
            /**
             * Signal Id
             * Format: uuid
             */
            signal_id: string;
            /** Signal Strength At Selection */
            signal_strength_at_selection: number | null;
            /** Source Keys */
            source_keys: string[];
            /** Strength Stratum */
            strength_stratum: string | null;
            /** Timing At Selection */
            timing_at_selection: number | null;
            /** Verdict */
            verdict: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /** Access Method */
            access_method: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Name */
            name: string;
            /** Next Run At */
            next_run_at: string | null;
            /** Poll Interval Minutes */
            poll_interval_minutes: number;
            /** Scope */
            scope: string;
            /** Source Type */
            source_type: string;
            /** Status */
            status: string;
        };
        /** SourceRunOut */
        SourceRunOut: {
            /** Completed At */
            completed_at: string | null;
            /** Completeness Rule Version */
            completeness_rule_version: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error Message */
            error_message: string | null;
            /** Execution Status */
            execution_status: string;
            /** Hit Result Limit */
            hit_result_limit: boolean | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Inventory Scope Complete */
            inventory_scope_complete: boolean | null;
            /** Items Changed */
            items_changed: number;
            /** Items New */
            items_new: number;
            /** Items Received */
            items_received: number | null;
            /** Items Removed */
            items_removed: number;
            /** Items Reported */
            items_reported: number | null;
            /** Items Seen */
            items_seen: number;
            /** Items Unchanged */
            items_unchanged: number;
            /** Pages Expected */
            pages_expected: number | null;
            /** Pages Received */
            pages_received: number | null;
            /** Pagination Complete */
            pagination_complete: boolean | null;
            /** Removal Candidates */
            removal_candidates: number;
            /** Requests Attempted */
            requests_attempted: number | null;
            /** Requests Failed */
            requests_failed: number | null;
            /** Requests Succeeded */
            requests_succeeded: number | null;
            /** Snapshot Evidence */
            snapshot_evidence: {
                [key: string]: unknown;
            };
            /** Snapshot Reasons */
            snapshot_reasons: string[];
            /** Snapshot Status */
            snapshot_status: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Name */
            source_name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Trigger Type */
            trigger_type: string;
        };
        /** SpatialFeatureList */
        SpatialFeatureList: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["SpatialFeatureOut"][];
        };
        /** SpatialFeatureOut */
        SpatialFeatureOut: {
            /** Activity Code */
            activity_code: number | null;
            /** Activity Label */
            activity_label: string | null;
            /** Attribution */
            attribution: string;
            /** Data Mode */
            data_mode: string;
            /** Dataset Key */
            dataset_key: string;
            /** Feature Type */
            feature_type: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Baseline */
            is_baseline: boolean;
            /** Municipality Code */
            municipality_code: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Source */
            source: string;
            /** Source Item Id */
            source_item_id: string;
            /** Source Modified At */
            source_modified_at: string | null;
            /** Status Code */
            status_code: number;
            /** Status Label */
            status_label: string;
            /** Subtype Code */
            subtype_code: number;
            /** Subtype Label */
            subtype_label: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TimingFactOut */
        TimingFactOut: {
            /** Conflicting Dates */
            conflicting_dates: string[];
            /** Date */
            date: string | null;
            /** Observation Ids */
            observation_ids: string[];
            /** State */
            state: string;
            /** Type */
            type: string;
            /** Warnings */
            warnings: string[];
        };
        /** ValidationBatchOut */
        ValidationBatchOut: {
            /** City Id */
            city_id: number;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Definition Set Hash */
            definition_set_hash: string | null;
            /** Dimension Scope Key */
            dimension_scope_key: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issue Counts */
            issue_counts: {
                [key: string]: number;
            };
            /** Items */
            items: components["schemas"]["SignalValidationOut"][];
            /** Name */
            name: string;
            /** Pending Count */
            pending_count: number;
            /** Population Size */
            population_size: number;
            /** Reviewed Count */
            reviewed_count: number;
            /** Rule Version */
            rule_version: string;
            /** Score As Of Date */
            score_as_of_date: string | null;
            /** Score Run Id */
            score_run_id: string | null;
            /** Seed */
            seed: string;
            /** Selection Manifest */
            selection_manifest: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Target Size */
            target_size: number;
            /** Verdict Counts */
            verdict_counts: {
                [key: string]: number;
            };
        };
        /** ValidationBatchSummaryOut */
        ValidationBatchSummaryOut: {
            /** City Id */
            city_id: number;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Definition Set Hash */
            definition_set_hash: string | null;
            /** Dimension Scope Key */
            dimension_scope_key: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issue Counts */
            issue_counts: {
                [key: string]: number;
            };
            /** Name */
            name: string;
            /** Pending Count */
            pending_count: number;
            /** Population Size */
            population_size: number;
            /** Reviewed Count */
            reviewed_count: number;
            /** Rule Version */
            rule_version: string;
            /** Score As Of Date */
            score_as_of_date: string | null;
            /** Score Run Id */
            score_run_id: string | null;
            /** Seed */
            seed: string;
            /** Status */
            status: string;
            /** Target Size */
            target_size: number;
            /** Verdict Counts */
            verdict_counts: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityOut"][];
                };
            };
        };
    };
    checkHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    listHousingProviders: {
        parameters: {
            query?: {
                city_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HousingProviderList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getLeadTimeSummary: {
        parameters: {
            query?: {
                source_key?: string | null;
                classification_tag?: string | null;
                listing_status?: ("ACTIVE" | "REMOVAL_CANDIDATE" | "REMOVED") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadTimeSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getOutcomeSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeSummaryOut"];
                };
            };
        };
    };
    recordPilotActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PilotActivityUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotActivityRecordedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPilotMetrics: {
        parameters: {
            query: {
                pilot_key: string;
                cohort_version: string;
                cohort_as_of_date: string;
                dimension_scope_key: string;
                score_run_id: string;
                score_as_of_date: string;
                definition_set_hash: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotMetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listPilotSignals: {
        parameters: {
            query?: {
                as_of?: string | null;
                address_query?: string | null;
                pilot_key?: string | null;
                review_status?: "ALL" | "REVIEWED" | "UNREVIEWED";
                strength_band?: ("LOW" | "MEDIUM" | "HIGH") | null;
                signal_type?: string | null;
                from?: string | null;
                to?: string | null;
                property_type?: string | null;
                min_rooms?: number | string | null;
                max_rooms?: number | string | null;
                min_area_m2?: number | string | null;
                max_area_m2?: number | string | null;
                center_latitude?: number | string | null;
                center_longitude?: number | string | null;
                radius_km?: number | string | null;
                sort?: "PRIORITY" | "MOVE_WINDOW" | "NEWEST";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotSignalListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPilotSignalFeedback: {
        parameters: {
            query: {
                pilot_key: string;
                cohort_version: string;
                cohort_as_of_date: string;
                dimension_scope_key: string;
                score_run_id: string;
                score_as_of_date: string;
                definition_set_hash: string;
            };
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotFeedbackOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsertPilotSignalFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PilotFeedbackUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PilotFeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getQualitySummary: {
        parameters: {
            query?: {
                city_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualitySummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRentalCoverage: {
        parameters: {
            query?: {
                city_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentalCoverageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRentalListings: {
        parameters: {
            query?: {
                status?: string | null;
                provider?: string | null;
                data_mode?: ("fixture" | "live") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentalListingList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRentalListingClassifications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentalListingClassificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRentalListingMeasurements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingMeasurementOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRentalProjects: {
        parameters: {
            query?: {
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentalProjectList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getScoreActivationSet: {
        parameters: {
            query?: {
                city_id?: number;
            };
            header?: never;
            path: {
                scope_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreActivationSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getActiveSignalDimensions: {
        parameters: {
            query?: {
                city_id?: number;
            };
            header?: never;
            path: {
                scope_key: string;
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalDimensionSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listScoreRuns: {
        parameters: {
            query?: {
                city_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getScoreRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getScoreRunSignalDimensions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalDimensionSetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSignals: {
        parameters: {
            query?: {
                city_id?: number | null;
                min_strength?: number;
                signal_type?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSignalOutcomes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalOutcomeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSourceRuns: {
        parameters: {
            query?: {
                limit?: number;
                source_id?: string | null;
                status?: ("RUNNING" | "SUCCESS" | "FAILED") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    getSourceLifecycleReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleReadinessOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSpatialFeatures: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialFeatureList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listValidationBatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationBatchSummaryOut"][];
                };
            };
        };
    };
    getValidationBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
