import enum


class EventType(enum.StrEnum):
    RENTAL_LISTED = "RENTAL_LISTED"
    LISTING_REMOVED = "LISTING_REMOVED"
    NEW_BUILD_MOVE_IN = "NEW_BUILD_MOVE_IN"
    SALE_LISTED = "SALE_LISTED"
    SALE_SOLD = "SALE_SOLD"
    LEASE_TERMINATED = "LEASE_TERMINATED"
    PROPERTY_TRANSFERRED = "PROPERTY_TRANSFERRED"
