import enum


class SignalType(enum.StrEnum):
    LIKELY_TENANT_MOVE_OUT = "LIKELY_TENANT_MOVE_OUT"
    LIKELY_HOMEOWNER_MOVE = "LIKELY_HOMEOWNER_MOVE"
    NEW_BUILD_MOVE_IN = "NEW_BUILD_MOVE_IN"
    POTENTIAL_RENTAL_TENANCY_CHANGE = "POTENTIAL_RENTAL_TENANCY_CHANGE"
    POTENTIAL_NEW_BUILD_MOVE_IN = "POTENTIAL_NEW_BUILD_MOVE_IN"
    LIKELY_RENTAL_TURNOVER = "LIKELY_RENTAL_TURNOVER"
